### ISSUE TITLE
Failed to initialize the ADM.Aborted

### ISSUE THREAD

**Issue by indrek-sunter** [zxbase/zxbase_flutter_ui#1]
Hi,
I like the concept of zxbase a lot, thank you for creating it!

I installed zxbase on Ubuntu 18.04 via Snap.

    $ snap install zxbase
    zxbase 3.1.1 from Zxbase LLC (zxbase) installed

However, it crashes on start:

    $ zxbase
    
    (zxbase:11434): Gtk-WARNING **: 08:40:39.853: Theme parsing error: gtk.css:1374:85: 'font-feature-settings' is not a valid property name
    
    
    #
    # Fatal error in: ../../media/engine/adm_helpers.cc, line 39
    # last system error: 88
    # Check failed: 0 == adm->Init() (0 vs. -1)
    # Failed to initialize the ADM.Aborted (core dumped)

Might there be any dependencies which I'm missing?

**Comment by arielt** [comment]
It most likely has to do with snap audio-playback connection.
You will need to check that pulseaudio is installed on your system and audio-playback is connected to zxbase snap.

**Comment by arielt** [comment]
Closing it for now, please let me know if that's still an issue.
